name: Historypin
favicon: null
layout_spectrum: 0.20885
typography_spectrum: 0.69522
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#5C5C5C'
    - '#EC008C'
    - '#FFE168'
  brandStrength: 0.6003584
  lightness: 0.7992831
  saturation: 0.6415771
  rhythmicContrast: 0.3960573
purpose: []
