color:
  saturation: 0.6415771
  brandStrength: 0.6003584
  rhythmicContrast: 0.3960573
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#5C5C5C'
    - '#EC008C'
    - '#FFE168'
  lightness: 0.7992831
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.4032258
typography_spectrum: 0.4784946
name: Historypin
