favicon: null
name: Historypin
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.2032041
  brandStrength: 0.6003584
  lightness: 0.3979764
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#5C5C5C'
    - '#EC008C'
    - '#FFE168'
  rhythmicContrast: 0.237774
typography_spectrum: 0.69522
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.20885
analytics:
  twitter: null
  google: null
  facebook: null
